### ISSUE TITLE
Incompatible with typescript 3.8.x

### ISSUE THREAD

**Issue by core-process** [slikts/queueable#213]
For some reason ```EventMap``` is expanded in line 6 of ```dist/types/fromDom.d.ts```. This results in an incompatibility with Typescript 3.8.x, since the published version seems to be compiled with an older version.

**Comment by moczix** [comment]
yup i got this same i guess
```node_modules/queueable/dist/types/fromDom.d.ts:6:1485 - error TS2536: Type 'T' cannot be used to index type 'GlobalEventHandlersEventMap'.```

**Comment by slikts** [comment]
I tried it locally and it should be fixed in [v4.1.4](https://github.com/slikts/queueable/releases/tag/v4.1.4); thanks for reporting.

**Comment by moczix** [comment]
i confirm, with 4.1.4 works fine. Thanks
